# Build settings
markdown: kramdown
url: https://taut.rocks
baseurl: /
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]

extlinks:
  attributes: {rel: nofollow, target: _blank}
  check_links: false #local
#prod:  check_links: true
  rel_exclude: ['g3rv4.com']

exclude: ["assets/less"]
